/**
 * The SFX cache (#68, SPEC.md §8.2: "the SFX cache searches Qdrant first at a 0.94
 * similarity threshold"). Same machinery and the same threshold as the image similarity
 * cache in ../similarity.ts - `SIMILARITY_THRESHOLD` is imported from there rather than
 * restated, so the two caches can never drift onto different numbers - but a dedicated
 * Qdrant collection: an ambient layer's payload (one media_asset id, a loop flag) has no
 * `ImageFeature`-shaped `feature` column to filter on, and the two media kinds have no
 * reason to share a collection just because they share a threshold.
 *
 * Scoped per universe, like the image cache, even though ai-game's own SFX cache was
 * global across every session: `media_asset.universe_id` is NOT NULL here (packages/db/
 * src/schema/media.ts), so a cache hit has to resolve to a row the requesting universe
 * actually owns. A generic "rain on leaves" layer generated for one universe is not
 * reused verbatim by another one's request under this design - see this package's report
 * for why a global cross-universe cache was not built instead.
 */
import {
	createVectorClient,
	ensureCollection,
	queryPoints,
	upsertPoints,
	type QdrantClient
} from '@canonry/vector';
import { SIMILARITY_THRESHOLD } from '../similarity.js';

export { SIMILARITY_THRESHOLD };
export type { QdrantClient };

/** One collection for the whole deployment, distinguished by payload filters - the same
 * reasoning as MEDIA_SIMILARITY_COLLECTION in ../similarity.ts. */
export const AUDIO_LAYER_SIMILARITY_COLLECTION = 'AudioLayerSimilarity';

interface AudioSimilarityPayload {
	universeId: string;
	/** Whether the cached file was generated as a seamless loop (a continuous layer) or
	 * not (oneshot/interval). A "rain, looping" file and a "rain, one strike" file are
	 * not interchangeable even at a high prompt-embedding similarity, so this is a filter
	 * leaf here exactly as it was a search parameter in ai-game's searchSfxCache. */
	loop: boolean;
	mediaAssetId: string;
}

function parseAudioSimilarityPayload(
	value: Record<string, unknown>
): AudioSimilarityPayload | null {
	if (typeof value.universeId !== 'string') return null;
	if (typeof value.loop !== 'boolean') return null;
	if (typeof value.mediaAssetId !== 'string') return null;
	return { universeId: value.universeId, loop: value.loop, mediaAssetId: value.mediaAssetId };
}

export interface AudioSimilarityCacheDeps {
	client: QdrantClient;
	/** Must match whatever EmbeddingProvider produces - same contract as
	 * SimilarityCacheDeps in ../similarity.ts. */
	vectorSize: number;
}

async function ensureReady(deps: AudioSimilarityCacheDeps): Promise<void> {
	await ensureCollection(deps.client, {
		name: AUDIO_LAYER_SIMILARITY_COLLECTION,
		vectorSize: deps.vectorSize
	});
}

export interface AudioSimilarityHit {
	pointId: string;
	score: number;
	mediaAssetId: string;
}

export interface FindSimilarAudioLayerInput {
	vector: number[];
	universeId: string;
	loop: boolean;
}

/** Null means a genuine miss (nothing scored at or above 0.94), not an error - mirrors
 * findSimilarMedia's own contract in ../similarity.ts. */
export async function findSimilarAudioLayer(
	deps: AudioSimilarityCacheDeps,
	input: FindSimilarAudioLayerInput
): Promise<AudioSimilarityHit | null> {
	await ensureReady(deps);
	const hits = await queryPoints(deps.client, AUDIO_LAYER_SIMILARITY_COLLECTION, {
		vector: input.vector,
		filter: {
			must: [
				{ key: 'universeId', value: input.universeId },
				{ key: 'loop', value: input.loop }
			]
		},
		limit: 1,
		scoreThreshold: SIMILARITY_THRESHOLD
	});
	const best = hits[0];
	if (!best) return null;
	const payload = parseAudioSimilarityPayload(best.payload);
	if (!payload) return null;
	return { pointId: best.id, score: best.score, mediaAssetId: payload.mediaAssetId };
}

export interface RecordAudioLayerVectorInput {
	/** Generated by the caller up front so it can also be stamped onto the new
	 * media_asset row as similarity_key before this function runs - see generate.ts. */
	pointId: string;
	vector: number[];
	universeId: string;
	loop: boolean;
	mediaAssetId: string;
}

/** Called exactly once per successful generation, never on a cache hit - same contract
 * as recordMediaVector in ../similarity.ts. */
export async function recordAudioLayerVector(
	deps: AudioSimilarityCacheDeps,
	input: RecordAudioLayerVectorInput
): Promise<void> {
	await ensureReady(deps);
	await upsertPoints(deps.client, AUDIO_LAYER_SIMILARITY_COLLECTION, [
		{
			id: input.pointId,
			vector: input.vector,
			payload: {
				universeId: input.universeId,
				loop: input.loop,
				mediaAssetId: input.mediaAssetId
			}
		}
	]);
}
