#!/usr/bin/env bash
#
# Builds the wasm reader and writes it into `src/onestore-wasm.generated.ts`, which is
# committed. Issue #603.
#
# Why the artefact is committed rather than built by CI and by the Docker image
# -----------------------------------------------------------------------------
# `docker/Dockerfile`'s runtime stage carries only `apps/web/build`, which is Vite's
# adapter-node output, plus a pruned `node_modules`. Vite inlines source-exported
# workspace packages such as `@canonry/import` straight into `build/server/chunks`, so a
# loose `.wasm` file living in this directory reaches neither the image nor a `pnpm dev`
# run, and making it reach both means an asset pipeline that has to resolve identically
# under `vite dev`, adapter-node, vitest and `packages/bench`. Base64 inside a `.ts`
# module is inlined like any other source, so all four work with no Vite config and no
# Dockerfile change, and neither pipeline needs a Rust toolchain.
#
# The cost of committing generated output is that it can go stale, and this repository
# already has the answer to that: `src/playbooks.generated.ts` is committed and guarded by
# regenerating it in CI and failing on `git diff --exit-code`. The `wasm` job in
# `.github/workflows/ci.yml` does exactly that for this file. So Rust is a verification
# dependency here and never a build dependency.
#
# Reproducibility
# ---------------
# Two clean builds have to agree byte for byte or that guard is worthless. Three things
# make them agree: `rust-toolchain.toml` pins the compiler, `Cargo.lock` pins the whole
# dependency tree, and `--remap-path-prefix` rewrites the two absolute paths rustc would
# otherwise bake into panic messages (the crates.io registry and this directory). Without
# the remap the artefact carries the building user's home directory, which is both
# irreproducible and something no committed file should hold. `trim-paths` would be the
# tidier way to say this and is not stable in Cargo 1.96.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$here"

target=wasm32-unknown-unknown
out="$here/../src/onestore-wasm.generated.ts"
wasm="$here/target/$target/release/canonry_onestore.wasm"

if ! command -v cargo >/dev/null 2>&1; then
	echo "cargo not found. This script is only needed when the Rust source changes;" >&2
	echo "the built artefact is committed at src/onestore-wasm.generated.ts." >&2
	exit 1
fi

rustup target add "$target" >/dev/null 2>&1 || true

# `${CARGO_HOME:-$HOME/.cargo}` rather than a bare `$HOME`: a CI runner and this devbox
# disagree about where the registry lives, and remapping the wrong prefix silently leaves
# the real one in the binary.
cargo_home="${CARGO_HOME:-$HOME/.cargo}"
RUSTFLAGS="--remap-path-prefix=$cargo_home/registry/src=/registry --remap-path-prefix=$here=/crate" \
	cargo build --release --target "$target" --locked

size=$(wc -c <"$wasm")
sha=$(sha256sum "$wasm" | cut -d' ' -f1)

node - "$wasm" "$out" "$size" "$sha" <<'NODE'
const fs = require('node:fs');
const zlib = require('node:zlib');

const [, , wasmPath, outPath, size, sha] = process.argv;
const raw = fs.readFileSync(wasmPath);
// Brotli at quality 11 over gzip: 227KB against 290KB on this artefact, and
// `zlib.brotliDecompressSync` is in Node's standard library, so the reader adds no
// dependency to decompress it.
const packed = zlib.brotliCompressSync(raw, {
	params: {
		[zlib.constants.BROTLI_PARAM_QUALITY]: 11,
		[zlib.constants.BROTLI_PARAM_SIZE_HINT]: raw.length
	}
});
const b64 = packed.toString('base64');

// Wrapped so the file is diffable and so Prettier has nothing to reformat: a single
// 300KB line would be rewritten by `prettier --write` and the CI guard would then see a
// diff it could never satisfy.
const lines = [];
for (let i = 0; i < b64.length; i += 116) lines.push(`\t'${b64.slice(i, i + 116)}' +`);
lines[lines.length - 1] = lines[lines.length - 1].replace(/ \+$/, ';');

const header = [
	'/**',
	' * Generated by `packages/import/onestore/build.sh`. Do not edit.',
	' *',
	' * The OneNote [MS-ONESTORE] reader, `packages/import/onestore` built for',
	' * wasm32-unknown-unknown, brotli-compressed and base64-encoded. That script\u2019s header',
	' * explains why the artefact is committed instead of built in CI and in the Docker',
	' * image, and `docs/onenote-export.md` carries the measurement behind the reader.',
	' *',
	' * raw    ' + size + ' bytes',
	' * sha256 ' + sha,
	' */',
	'export const ONESTORE_WASM_BROTLI_BASE64 ='
];

fs.writeFileSync(outPath, header.join('\n') + '\n' + lines.join('\n') + '\n');

console.log(
	`wrote ${outPath}\n  raw ${size} bytes, brotli ${packed.length}, base64 ${b64.length}\n  sha256 ${sha}`
);
NODE
