/**
 * DB-driven image model resolution (#64, SPEC.md §9: "the active model lives in the
 * database and is the one always used, switchable from an admin surface without a
 * deploy"). The image-specific sibling of @canonry/ai's resolveModel/model_config: that
 * one resolves per *purpose* (cheap/premium/multimodal/embedding/image) and knows nothing
 * about `image_model_config`'s per-*feature* routing (portrait vs the four-variant
 * batch), which is what this module reads instead.
 */
import { activeImageModelRow, type Db, type ImageModelRow } from '@canonry/db';
import type { ImageFeature } from '@canonry/db/schema';
import { isCurrency, type Currency, type ResolvedModel } from '@canonry/ai';

export type { ImageModelRow };

export interface ImageModelParams {
	/** The currency `pricePerImage` is stated in - the provider's own price, never
	 * pre-converted (issue #132). Defaults to EUR when absent, the same convention
	 * `@canonry/ai`'s `ModelParams.currency` documents. */
	currency?: Currency;
	/** Our own cost per image, in whichever currency `currency` declares - what we pay
	 * the provider. Never the user-facing credit price; operation_price owns that
	 * (issue #113), and the two are deliberately different numbers. */
	pricePerImage?: number;
	creditsPerEur?: number;
	/** The shape this feature asks its model for, as Replicate's own `aspect_ratio` value
	 * (#332). It lives on the row rather than in code because it is a property of the pair
	 * "this feature, generated by this model": a portrait is 3:2 because that is the shape
	 * the cover band crops it to (#284), and whether the configured model will honour that
	 * is its own schema's business - `assertAspectRatioSupported` (aspect-ratio.ts) is what
	 * checks the two still agree after an /admin/models swap. Absent means "leave the
	 * model's default alone", which is what `portrait` and `variants` said, unintentionally,
	 * from migration 0011 until migration 0045. */
	aspectRatio?: string;
}

export function readImageModelParams(value: unknown): ImageModelParams {
	if (typeof value !== 'object' || value === null) return {};
	const record = value as Record<string, unknown>;
	const params: ImageModelParams = {};
	if (typeof record.currency === 'string' && isCurrency(record.currency))
		params.currency = record.currency;
	if (typeof record.pricePerImage === 'number') params.pricePerImage = record.pricePerImage;
	if (typeof record.creditsPerEur === 'number') params.creditsPerEur = record.creditsPerEur;
	if (typeof record.aspectRatio === 'string') params.aspectRatio = record.aspectRatio;
	return params;
}

export class ImageModelNotConfiguredError extends Error {
	constructor(feature: ImageFeature) {
		super(`no active image_model_config row for feature "${feature}"`);
		this.name = 'ImageModelNotConfiguredError';
	}
}

/**
 * 30s TTL, mirroring @canonry/ai's resolveModel cache and for the same reason: this sits
 * on the hot "open the generate dialog" path, but an /admin/models save has to be visible
 * on the very next request either way - clearImageModelCache() is what that save calls,
 * the TTL only bounds staleness for an edit nobody explicitly cleared the cache for.
 */
const CACHE_TTL_MS = 30_000;

interface CacheEntry {
	value: ImageModelRow;
	expiresAt: number;
}

const cache = new Map<ImageFeature, CacheEntry>();

export function clearImageModelCache(): void {
	cache.clear();
}

export async function resolveImageModelRow(db: Db, feature: ImageFeature): Promise<ImageModelRow> {
	const now = Date.now();
	const cached = cache.get(feature);
	if (cached && cached.expiresAt > now) return cached.value;

	const row = await activeImageModelRow(db, feature);
	if (!row) throw new ImageModelNotConfiguredError(feature);
	cache.set(feature, { value: row, expiresAt: now + CACHE_TTL_MS });
	return row;
}

/** Adapts an image_model_config row into @canonry/ai's ResolvedModel shape so
 * generateImage()/withUsage() can be called unchanged. `purpose` is always 'image' here -
 * accurate (model_config's own 'image' purpose names the same bucket) even though this
 * module's feature-level routing is one level more specific than model_config knows about.
 *
 * Split from `resolveImageModel` for `generateImages`, which needs the row's own
 * `aspectRatio` (#332) as well as the model and should not pay for, or risk disagreeing
 * with, a second resolution to get it. */
export function imageModelFromRow(row: ImageModelRow): ResolvedModel {
	return {
		purpose: 'image',
		provider: row.provider,
		modelId: row.modelId,
		params: readImageModelParams(row.params)
	};
}

export async function resolveImageModel(db: Db, feature: ImageFeature): Promise<ResolvedModel> {
	return imageModelFromRow(await resolveImageModelRow(db, feature));
}
