/**
 * The similarity cache (#67, SPEC.md §8.2's pattern reused for media, §9's threshold).
 * Before paying a provider for a new image, the caller embeds the built prompt and this
 * module searches Qdrant for a near-identical prompt already generated in the same
 * universe for the same feature; a hit names the media_asset ids that prompt produced
 * instead of spending again. A miss upserts one point only *after* the images are
 * actually generated and stored (see generate.ts), so a failed generation never poisons
 * the cache with a point that has no files behind it.
 */
import {
	createVectorClient,
	ensureCollection,
	queryPoints,
	upsertPoints,
	type QdrantClient
} from '@canonry/vector';
import type { ImageFeature } from '@canonry/db/schema';

export { createVectorClient };
export type { QdrantClient };

/** SPEC.md §8.2: "the SFX cache searches Qdrant first at a 0.94 similarity threshold" -
 * SPEC.md §9 names the same number for images, and issue #67 covers media generally. */
export const SIMILARITY_THRESHOLD = 0.94;

/**
 * One collection per embedding model, holding every universe and feature, which are
 * distinguished by payload filters rather than by name. Nothing about this cache is
 * per-universe, so the name is not; but the vector width is a property of the model, and two
 * writers at different widths cannot share a collection.
 *
 * The model used to be absent from the name, and that was a real defect rather than a tidiness
 * question: issue #125's switch to a 3072-dimension model left the deployment's 256-dimension
 * collection in place, and app and tests then took turns deleting and recreating one name at two
 * widths. Same reasoning as `loreCollectionName` (SPEC.md §11.3), which had it right first.
 */
export function mediaSimilarityCollectionName(provider: string, modelId: string): string {
	return `MediaPromptSimilarity_${provider}_${modelId}`;
}

interface SimilarityPayload {
	universeId: string;
	feature: ImageFeature;
	mediaAssetIds: string[];
}

function isImageFeature(value: string): value is ImageFeature {
	return value === 'portrait' || value === 'variants' || value === 'scene';
}

function parseSimilarityPayload(value: Record<string, unknown>): SimilarityPayload | null {
	if (typeof value.universeId !== 'string') return null;
	if (typeof value.feature !== 'string' || !isImageFeature(value.feature)) return null;
	if (!Array.isArray(value.mediaAssetIds)) return null;
	const mediaAssetIds = value.mediaAssetIds;
	if (!mediaAssetIds.every((id): id is string => typeof id === 'string')) return null;
	return { universeId: value.universeId, feature: value.feature, mediaAssetIds };
}

export interface SimilarityCacheDeps {
	client: QdrantClient;
	/** Built with `mediaSimilarityCollectionName` from whichever embedding model the caller's
	 * `EmbeddingProvider` actually uses, so the name and the width can never disagree. */
	collection: string;
	/** The embedding model's output dimensionality - Qdrant needs it up front to create
	 * the collection. Must match whatever EmbeddingProvider is passed to generate.ts. */
	vectorSize: number;
}

async function ensureReady(deps: SimilarityCacheDeps): Promise<void> {
	await ensureCollection(deps.client, {
		// Recreated rather than guarded: this is a cache of prompt embeddings, so a model change costs
		// one re-embed. Keeping a stale-width collection would reject every upsert instead.
		onDimensionMismatch: 'recreate',
		name: deps.collection,
		vectorSize: deps.vectorSize
	});
}

export interface SimilarityHit {
	pointId: string;
	score: number;
	mediaAssetIds: string[];
}

export interface FindSimilarInput {
	vector: number[];
	universeId: string;
	feature: ImageFeature;
}

/** Null means a genuine miss (nothing scored at or above the threshold), not an error. */
export async function findSimilarMedia(
	deps: SimilarityCacheDeps,
	input: FindSimilarInput
): Promise<SimilarityHit | null> {
	await ensureReady(deps);
	const hits = await queryPoints(deps.client, deps.collection, {
		vector: input.vector,
		filter: {
			must: [
				{ key: 'universeId', value: input.universeId },
				{ key: 'feature', value: input.feature }
			]
		},
		limit: 1,
		scoreThreshold: SIMILARITY_THRESHOLD
	});
	const best = hits[0];
	if (!best) return null;
	const payload = parseSimilarityPayload(best.payload);
	if (!payload) return null;
	return { pointId: best.id, score: best.score, mediaAssetIds: payload.mediaAssetIds };
}

export interface RecordVectorInput {
	/** Generated by the caller up front (generate.ts) so it can also be stamped onto each
	 * new media_asset row as similarity_key before this function ever runs - no second
	 * "now go back and set the key" write is needed. */
	pointId: string;
	vector: number[];
	universeId: string;
	feature: ImageFeature;
	mediaAssetIds: string[];
}

/** Called exactly once per successful generation, never on a cache hit. */
export async function recordMediaVector(
	deps: SimilarityCacheDeps,
	input: RecordVectorInput
): Promise<void> {
	await ensureReady(deps);
	await upsertPoints(deps.client, deps.collection, [
		{
			id: input.pointId,
			vector: input.vector,
			payload: {
				universeId: input.universeId,
				feature: input.feature,
				mediaAssetIds: input.mediaAssetIds
			}
		}
	]);
}
