// Better Auth 1.7.1 owns these four tables and their column names, so nothing here is
// a design choice: the shapes come from the library's own zod schemas
// (packages/core/src/db/schema/{user,session,account,verification}.ts upstream). Ids are
// text because Better Auth generates them, not the database.
//
// Kept in this repository rather than generated by its CLI on purpose: the CLI pulls
// Prisma and better-sqlite3 in as build dependencies, and the schema is stable enough
// that carrying two extra native builds for it is a bad trade. If a Better Auth upgrade
// changes a column, this file is the thing to diff against the release notes.
//
// "Stable enough" cost a release on 1.7 (issue #674) and the shape of that failure is worth
// keeping: the field list this file has to match is `getAuthTables` in
// `@better-auth/core/db`, the drizzle adapter compares it against these tables at call time
// rather than at build time, and a minor version that adds one required field therefore
// turns every affected call into a 500 that nothing in `pnpm check` can see.
//
// `../../test/auth-schema.test.ts` is now that check, and it is the file to read before
// editing this one (issue #685). It calls `getAuthTables` on the installed version and
// compares what it declares against these four tables, in both directions, plus type,
// nullability and uniqueness, so a bump that moves a column fails there by name instead of
// at request time. A column of ours rather than Better Auth's - `user.locale`,
// `user.handle` - has to be listed in that file's own allowlist with a reason, which is the
// only maintenance it asks for.
import { sql } from 'drizzle-orm';
import { boolean, check, pgTable, text, timestamp, uniqueIndex } from 'drizzle-orm/pg-core';
import {
	HANDLE_MAX_LENGTH,
	HANDLE_MIN_LENGTH,
	HANDLE_PATTERN_SOURCE,
	RESERVED_HANDLES
} from '../handles.js';

// A Postgres `array[...]` literal built from the one list in `../handles.js`, so the check
// constraint below and the form's own validation cannot drift: adding a reserved word is a
// migration, which is what issue #158 asks for, and it is one edit rather than two.
const RESERVED_HANDLES_ARRAY = sql.raw(
	`array[${RESERVED_HANDLES.map((handle) => `'${handle}'`).join(', ')}]`
);

export const user = pgTable(
	'user',
	{
		id: text('id').primaryKey(),
		name: text('name').notNull(),
		email: text('email').notNull().unique(),
		emailVerified: boolean('email_verified').notNull().default(false),
		image: text('image'),
		// SPEC.md §17: the interface language is a preference on the account rather than a cookie,
		// so it follows the GM to the phone at the table, which is where half of table mode is
		// used. Null means nobody has chosen yet and the request's Accept-Language decides; an
		// explicit choice beats that header forever after. A Better Auth additional field, which
		// is why it lives on this table rather than in a settings table of our own.
		locale: text('locale'),
		// Issue #158: the public profile at `/u/<handle>`. Distinct from `name`, which is and
		// stays a display name - a person is printed by `name` and addressed by `handle`, and
		// neither is derived from the other.
		//
		// Null means no handle, which means no profile: decision recorded on #158, the handle is
		// chosen later and opt-in, never at sign-up, so an account that never wanted one is
		// unreachable rather than published under something we made up for it. A unique index
		// ignores nulls in Postgres, so every account can sit at null at once.
		//
		// **Stored as entered, unique and matched case-insensitively.** Both halves are
		// deliberate. Case is kept because a handle is how a person writes their own name in a
		// URL and lowering it silently is a product taking that away. Uniqueness and lookup
		// ignore case because `Lorenzo` and `lorenzo` being two people is a phishing surface,
		// not a feature, and because a handle gets read off a card and typed back with whatever
		// capitals the reader guessed - a URL that resolves only with the right shift key is a
		// broken URL. Hence `user_handle_lower_key` on `lower(handle)` rather than a plain
		// unique constraint, and hence `publicProfileByHandle` comparing on `lower` too.
		//
		// The reserved word list and the format live in `../handles.js` and are enforced here as
		// check constraints rather than only in the form that writes them, because #158's own
		// body says the list ships with the column: a reserved handle has to be impossible for
		// any writer, including a script and a future admin tool, not merely refused by one
		// screen.
		handle: text('handle'),
		createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
		updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow()
	},
	(t) => [
		uniqueIndex('user_handle_lower_key').on(sql`lower(${t.handle})`),
		check(
			'user_handle_format',
			sql`${t.handle} is null or (lower(${t.handle}) ~ ${sql.raw(`'^${HANDLE_PATTERN_SOURCE}$'`)} and char_length(${t.handle}) between ${sql.raw(String(HANDLE_MIN_LENGTH))} and ${sql.raw(String(HANDLE_MAX_LENGTH))})`
		),
		check(
			'user_handle_not_reserved',
			sql`${t.handle} is null or lower(${t.handle}) <> all (${RESERVED_HANDLES_ARRAY})`
		)
	]
);

export const session = pgTable(
	'session',
	{
		id: text('id').primaryKey(),
		userId: text('user_id')
			.notNull()
			.references(() => user.id, { onDelete: 'cascade' }),
		token: text('token').notNull(),
		expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
		ipAddress: text('ip_address'),
		userAgent: text('user_agent'),
		createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
		updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow()
	},
	(t) => [uniqueIndex('session_token_key').on(t.token)]
);

// One row per credential or social provider per user. `password` is only ever set for
// providerId 'credential'; the OAuth columns are only ever set for a social provider.
//
// `issuer` arrived with Better Auth 1.7 (issue #674), and it is the one column in this file
// whose absence was a runtime error rather than a type error: 1.7's `getAuthTables` declares
// it `required: true` on `account`, the drizzle adapter checks declared fields against this
// table at call time, and every credential sign-in and sign-up answered
// `BetterAuthError: The field "issuer" does not exist in the "account" Drizzle schema`
// instead of failing to compile. 1.7 recognises an external account by the pair
// (`issuer`, `accountId`) rather than by (`providerId`, `accountId`): `providerId` stays the
// local provider configuration, and `issuer` is the authority that assigned `accountId`.
// The values are the library's, not ours - `local:credential` for a password account (whose
// `accountId` is the linked user's own id), the provider's real OIDC issuer where it has one
// (`https://accounts.google.com`), and `local:oauth:<encodeURIComponent(providerId)>` for an
// OAuth provider without one. `packages/db/migrations/0053_account_issuer.sql` carries the
// backfill and refuses a provider it has no mapping for.
export const account = pgTable(
	'account',
	{
		id: text('id').primaryKey(),
		userId: text('user_id')
			.notNull()
			.references(() => user.id, { onDelete: 'cascade' }),
		accountId: text('account_id').notNull(),
		providerId: text('provider_id').notNull(),
		issuer: text('issuer').notNull(),
		accessToken: text('access_token'),
		refreshToken: text('refresh_token'),
		idToken: text('id_token'),
		accessTokenExpiresAt: timestamp('access_token_expires_at', { withTimezone: true }),
		refreshTokenExpiresAt: timestamp('refresh_token_expires_at', { withTimezone: true }),
		scope: text('scope'),
		password: text('password'),
		createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
		updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow()
	},
	// 1.7's own account schema declares this index (unnamed, so the name is ours and follows
	// this file's `*_key` convention rather than the upgrade guide's `_uidx`). It is what makes
	// the identity pair an identity: without it the same provider account can be linked to two
	// users, which is the collision the migration checks for before it creates the index.
	(t) => [uniqueIndex('account_issuer_account_id_key').on(t.issuer, t.accountId)]
);

// Email verification codes and password reset tokens. Rows are short lived by design.
export const verification = pgTable('verification', {
	id: text('id').primaryKey(),
	identifier: text('identifier').notNull(),
	value: text('value').notNull(),
	expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
	createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
	updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow()
});
