// Better Auth 1.6.27 owns these four tables and their column names, so nothing here is
// a design choice: the shapes come from the library's own zod schemas
// (packages/core/src/db/schema/{user,session,account,verification}.ts upstream). Ids are
// text because Better Auth generates them, not the database.
//
// Kept in this repository rather than generated by its CLI on purpose: the CLI pulls
// Prisma and better-sqlite3 in as build dependencies, and the schema is stable enough
// that carrying two extra native builds for it is a bad trade. If a Better Auth upgrade
// changes a column, this file is the thing to diff against the release notes.
import { sql } from 'drizzle-orm';
import { boolean, check, pgTable, text, timestamp, uniqueIndex } from 'drizzle-orm/pg-core';
import {
	HANDLE_MAX_LENGTH,
	HANDLE_MIN_LENGTH,
	HANDLE_PATTERN_SOURCE,
	RESERVED_HANDLES
} from '../handles.js';

// A Postgres `array[...]` literal built from the one list in `../handles.js`, so the check
// constraint below and the form's own validation cannot drift: adding a reserved word is a
// migration, which is what issue #158 asks for, and it is one edit rather than two.
const RESERVED_HANDLES_ARRAY = sql.raw(
	`array[${RESERVED_HANDLES.map((handle) => `'${handle}'`).join(', ')}]`
);

export const user = pgTable(
	'user',
	{
		id: text('id').primaryKey(),
		name: text('name').notNull(),
		email: text('email').notNull().unique(),
		emailVerified: boolean('email_verified').notNull().default(false),
		image: text('image'),
		// SPEC.md §17: the interface language is a preference on the account rather than a cookie,
		// so it follows the GM to the phone at the table, which is where half of table mode is
		// used. Null means nobody has chosen yet and the request's Accept-Language decides; an
		// explicit choice beats that header forever after. A Better Auth additional field, which
		// is why it lives on this table rather than in a settings table of our own.
		locale: text('locale'),
		// Issue #158: the public profile at `/u/<handle>`. Distinct from `name`, which is and
		// stays a display name - a person is printed by `name` and addressed by `handle`, and
		// neither is derived from the other.
		//
		// Null means no handle, which means no profile: decision recorded on #158, the handle is
		// chosen later and opt-in, never at sign-up, so an account that never wanted one is
		// unreachable rather than published under something we made up for it. A unique index
		// ignores nulls in Postgres, so every account can sit at null at once.
		//
		// **Stored as entered, unique and matched case-insensitively.** Both halves are
		// deliberate. Case is kept because a handle is how a person writes their own name in a
		// URL and lowering it silently is a product taking that away. Uniqueness and lookup
		// ignore case because `Lorenzo` and `lorenzo` being two people is a phishing surface,
		// not a feature, and because a handle gets read off a card and typed back with whatever
		// capitals the reader guessed - a URL that resolves only with the right shift key is a
		// broken URL. Hence `user_handle_lower_key` on `lower(handle)` rather than a plain
		// unique constraint, and hence `publicProfileByHandle` comparing on `lower` too.
		//
		// The reserved word list and the format live in `../handles.js` and are enforced here as
		// check constraints rather than only in the form that writes them, because #158's own
		// body says the list ships with the column: a reserved handle has to be impossible for
		// any writer, including a script and a future admin tool, not merely refused by one
		// screen.
		handle: text('handle'),
		createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
		updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow()
	},
	(t) => [
		uniqueIndex('user_handle_lower_key').on(sql`lower(${t.handle})`),
		check(
			'user_handle_format',
			sql`${t.handle} is null or (lower(${t.handle}) ~ ${sql.raw(`'^${HANDLE_PATTERN_SOURCE}$'`)} and char_length(${t.handle}) between ${sql.raw(String(HANDLE_MIN_LENGTH))} and ${sql.raw(String(HANDLE_MAX_LENGTH))})`
		),
		check(
			'user_handle_not_reserved',
			sql`${t.handle} is null or lower(${t.handle}) <> all (${RESERVED_HANDLES_ARRAY})`
		)
	]
);

export const session = pgTable(
	'session',
	{
		id: text('id').primaryKey(),
		userId: text('user_id')
			.notNull()
			.references(() => user.id, { onDelete: 'cascade' }),
		token: text('token').notNull(),
		expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
		ipAddress: text('ip_address'),
		userAgent: text('user_agent'),
		createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
		updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow()
	},
	(t) => [uniqueIndex('session_token_key').on(t.token)]
);

// One row per credential or social provider per user. `password` is only ever set for
// providerId 'credential'; the OAuth columns are only ever set for a social provider.
export const account = pgTable('account', {
	id: text('id').primaryKey(),
	userId: text('user_id')
		.notNull()
		.references(() => user.id, { onDelete: 'cascade' }),
	accountId: text('account_id').notNull(),
	providerId: text('provider_id').notNull(),
	accessToken: text('access_token'),
	refreshToken: text('refresh_token'),
	idToken: text('id_token'),
	accessTokenExpiresAt: timestamp('access_token_expires_at', { withTimezone: true }),
	refreshTokenExpiresAt: timestamp('refresh_token_expires_at', { withTimezone: true }),
	scope: text('scope'),
	password: text('password'),
	createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
	updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow()
});

// Email verification codes and password reset tokens. Rows are short lived by design.
export const verification = pgTable('verification', {
	id: text('id').primaryKey(),
	identifier: text('identifier').notNull(),
	value: text('value').notNull(),
	expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
	createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
	updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow()
});
