// Better Auth 1.6.27 owns these four tables and their column names, so nothing here is
// a design choice: the shapes come from the library's own zod schemas
// (packages/core/src/db/schema/{user,session,account,verification}.ts upstream). Ids are
// text because Better Auth generates them, not the database.
//
// Kept in this repository rather than generated by its CLI on purpose: the CLI pulls
// Prisma and better-sqlite3 in as build dependencies, and the schema is stable enough
// that carrying two extra native builds for it is a bad trade. If a Better Auth upgrade
// changes a column, this file is the thing to diff against the release notes.
import { boolean, pgTable, text, timestamp, uniqueIndex } from 'drizzle-orm/pg-core';

export const user = pgTable('user', {
	id: text('id').primaryKey(),
	name: text('name').notNull(),
	email: text('email').notNull().unique(),
	emailVerified: boolean('email_verified').notNull().default(false),
	image: text('image'),
	// SPEC.md §17: the interface language is a preference on the account rather than a cookie,
	// so it follows the GM to the phone at the table, which is where half of table mode is
	// used. Null means nobody has chosen yet and the request's Accept-Language decides; an
	// explicit choice beats that header forever after. A Better Auth additional field, which
	// is why it lives on this table rather than in a settings table of our own.
	locale: text('locale'),
	createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
	updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow()
});

export const session = pgTable(
	'session',
	{
		id: text('id').primaryKey(),
		userId: text('user_id')
			.notNull()
			.references(() => user.id, { onDelete: 'cascade' }),
		token: text('token').notNull(),
		expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
		ipAddress: text('ip_address'),
		userAgent: text('user_agent'),
		createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
		updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow()
	},
	(t) => [uniqueIndex('session_token_key').on(t.token)]
);

// One row per credential or social provider per user. `password` is only ever set for
// providerId 'credential'; the OAuth columns are only ever set for a social provider.
export const account = pgTable('account', {
	id: text('id').primaryKey(),
	userId: text('user_id')
		.notNull()
		.references(() => user.id, { onDelete: 'cascade' }),
	accountId: text('account_id').notNull(),
	providerId: text('provider_id').notNull(),
	accessToken: text('access_token'),
	refreshToken: text('refresh_token'),
	idToken: text('id_token'),
	accessTokenExpiresAt: timestamp('access_token_expires_at', { withTimezone: true }),
	refreshTokenExpiresAt: timestamp('refresh_token_expires_at', { withTimezone: true }),
	scope: text('scope'),
	password: text('password'),
	createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
	updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow()
});

// Email verification codes and password reset tokens. Rows are short lived by design.
export const verification = pgTable('verification', {
	id: text('id').primaryKey(),
	identifier: text('identifier').notNull(),
	value: text('value').notNull(),
	expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
	createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
	updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow()
});
