/**
 * Issue #685: the guard for `src/schema/auth.ts`, which is hand-carried against Better
 * Auth's own table definitions rather than generated by its CLI. That file's doc comment
 * explains why (the CLI drags Prisma and better-sqlite3 in as build dependencies), and the
 * price of carrying it by hand is exactly this: the file is valid TypeScript whatever
 * Better Auth has since decided, so a disagreement between the two is invisible to
 * `pnpm check` and arrives as a 500 on the front door instead.
 *
 * Which is not hypothetical. 1.7 added a required `issuer` field to `account` (issue #674),
 * and because the drizzle adapter resolves a field to a column at call time
 * (`checkMissingFields` in `@better-auth/drizzle-adapter`, which is a plain
 * `schemaModel[fieldName]` lookup), every credential sign-in and sign-up answered
 * `BetterAuthError: The field "issuer" does not exist in the "account" Drizzle schema` for
 * as long as the bump was installed. A minor version, an auth outage, and nothing in the
 * type checker could see it.
 *
 * `getAuthTables` is the function the adapter validates against, re-exported from
 * `better-auth/db`, so this file asks the installed version what it declares and compares
 * it against the real drizzle tables, column by column. It is the cheap half of what the
 * CLI would have told us, and it fails naming the field, the table and the version that
 * declared it rather than at request time.
 *
 * ## What it checks
 *
 * - Every field `getAuthTables` declares has a column, for all four tables. That is the
 *   exact shape of #674.
 * - Every column we carry is either declared by Better Auth or listed in
 *   `OUR_OWN_COLUMNS` below with a reason. A surplus column is not automatically wrong -
 *   `user.locale` and `user.handle` are ours - but it is always a decision, so it is
 *   written down once rather than tolerated silently.
 * - Type and nullability, both of which the adapter also depends on even though it only
 *   checks names: a column that is `NOT NULL` where Better Auth stopped writing a value
 *   fails every insert, and a nullable column where Better Auth requires one hands a null
 *   to code that has no case for it.
 * - Uniqueness, wherever Better Auth declares it, either on a field or as a unique index.
 *   That is #684's second half: the `(issuer, accountId)` index is what makes the identity
 *   pair an identity, and a missing unique constraint lets two users own one login.
 * - An `id` column on each table. `getAuthTables` never declares one (Better Auth
 *   generates ids, so they are not part of its field list) and the adapter uses
 *   `schemaModel.id` regardless, so it is checked here rather than allowlisted below.
 *
 * ## What it deliberately does not check
 *
 * - Non-unique indexes. Better Auth sets `index: true` on `session.userId`,
 *   `account.userId` and `verification.identifier`, and we carry none of the three. That
 *   is a query-plan decision rather than drift: a missing index is slow, not broken, and
 *   asserting them would fail on a choice we made instead of on a change upstream.
 * - Foreign keys and their `onDelete`. Both `userId` fields declare a cascade and both
 *   have one, but a mismatch there is a data-integrity bug of ours, not the class of
 *   silent upstream change this file exists for.
 * - Defaults and column widths, which the adapter never reads.
 *
 * ## What it cannot see
 *
 * - Fields a plugin or an `additionalFields` entry would add. `getAuthTables` is a
 *   function of the options the app passes it, and this package cannot reach
 *   `apps/web`'s instance, so it is called here with empty options. That is exact today
 *   only because `apps/web` sets none of the option keys `buildAuthTables` reads, which is
 *   asserted where those options live, in
 *   `apps/web/src/lib/server/auth-options.test.ts`. If that test ever has to change, this
 *   file has to learn about the new fields in the same commit.
 * - The database. This compares two TypeScript declarations; whether a migration ever ran
 *   is `test/global-setup.ts`'s business and the migration tests'.
 * - The values in a column. `migrations/0053_account_issuer.sql` owns the `issuer`
 *   backfill and asserts its own correctness.
 */
import { readFileSync } from 'node:fs';
import { getAuthTables } from 'better-auth/db';
import { getTableColumns } from 'drizzle-orm';
import { getTableConfig, IndexedColumn, type PgTable } from 'drizzle-orm/pg-core';
import { describe, expect, it } from 'vitest';
import { account, session, user, verification } from '../src/schema/auth.js';

const SCHEMA_PATH = 'packages/db/src/schema/auth.ts';

/**
 * The installed version, named in every failure message: the field that broke #674 arrived
 * in a minor bump, so "which version declared this" is the first thing the next reader
 * needs and the last thing a stack trace carries. Read off disk rather than imported,
 * because `better-auth` does not export its own `package.json`.
 */
const manifest: unknown = JSON.parse(
	readFileSync(new URL('../node_modules/better-auth/package.json', import.meta.url), 'utf8')
);
if (!(typeof manifest === 'object' && manifest && 'version' in manifest))
	throw new Error('better-auth has no package.json version to name in a failure message');
const BETTER_AUTH_VERSION = String(manifest.version);

/**
 * Empty on purpose, and the one assumption this file rests on. See "What it cannot see"
 * above: `apps/web` passes none of the option keys `buildAuthTables` reads, so the
 * library's own defaults are exactly what our tables have to match.
 */
const AUTH_OPTIONS: Parameters<typeof getAuthTables>[0] = {};

const DECLARED = getAuthTables(AUTH_OPTIONS);

/** Keyed by Better Auth's model names, which are also ours: `usePlural` is off. */
const TABLES: Record<string, PgTable> = { user, session, account, verification };

/**
 * Columns that are ours rather than Better Auth's, each with the reason it exists. Kept
 * short on purpose: an entry here is a claim that a column is deliberately outside the
 * library's schema, and the alternative reading of a surplus column is that we are
 * carrying something a Better Auth upgrade dropped.
 */
const OUR_OWN_COLUMNS: Record<string, Record<string, string>> = {
	user: {
		locale:
			'SPEC.md §17: the interface language is a preference on the account, so it follows the GM to the phone at the table.',
		handle:
			'Issues #158 and #251: the public profile at /u/<handle>, opt-in and distinct from `name`.'
	},
	session: {},
	account: {},
	verification: {}
};

/**
 * Better Auth's field-type vocabulary against drizzle's `dataType`. The two agree on the
 * four scalar names our tables use, so the mapping is mostly identity; the collection
 * entries are here so that a plugin-shaped type does not read as a mismatch. An unknown
 * type is reported rather than skipped, because a type this file cannot compare is a hole
 * in the guard and the next reader should hear about it from a failure.
 */
const DRIZZLE_DATA_TYPE: Record<string, string> = {
	string: 'string',
	number: 'number',
	boolean: 'boolean',
	date: 'date',
	json: 'json',
	'string[]': 'array',
	'number[]': 'array'
};

/** The drizzle property key the adapter looks a declared field up by. */
function columnKey(field: string, attributes: { fieldName?: string }): string {
	return attributes.fieldName ?? field;
}

/**
 * A set of columns as one comparable string. Sorted, because uniqueness does not depend on
 * the order the columns were written in and a guard that thought otherwise would fail on
 * `(accountId, issuer)` for no reason.
 */
function normalizeColumnSet(names: string[]): string {
	return [...names].sort().join(',');
}

/** Every unique constraint on a table, as `normalizeColumnSet` strings. */
function uniqueColumnSets(table: PgTable): Set<string> {
	const config = getTableConfig(table);
	const sets = new Set<string>();
	for (const index of config.indexes) {
		if (!index.config.unique) continue;
		const names: string[] = [];
		// `IndexedColumn`, not `Column`: an index's own columns are a separate drizzle class that
		// carries the index's per-column options, and it is not in `Column`'s prototype chain.
		for (const column of index.config.columns)
			if (column instanceof IndexedColumn && typeof column.name === 'string')
				names.push(column.name);
		// An expression index has no column name to compare against - `user_handle_lower_key` is
		// on `lower(handle)` - and better-auth declares none, so it is not a candidate.
		if (names.length === index.config.columns.length) sets.add(normalizeColumnSet(names));
	}
	for (const constraint of config.uniqueConstraints)
		sets.add(normalizeColumnSet(constraint.columns.map((column) => column.name)));
	for (const column of Object.values(getTableColumns(table)))
		if (column.isUnique) sets.add(normalizeColumnSet([column.name]));
	return sets;
}

describe(`our drizzle auth schema against better-auth ${BETTER_AUTH_VERSION}`, () => {
	it('declares exactly the four tables this file knows about', () => {
		// A fifth table would mean Better Auth grew one (or an option turned one on), and every
		// assertion below would silently stop covering it.
		expect(Object.keys(DECLARED).sort()).toEqual(Object.keys(TABLES).sort());
	});

	it('has a column for every field better-auth declares', () => {
		const missing: string[] = [];
		for (const [model, table] of Object.entries(TABLES)) {
			const columns = getTableColumns(table);
			for (const [field, attributes] of Object.entries(DECLARED[model].fields)) {
				const key = columnKey(field, attributes);
				if (key in columns) continue;
				missing.push(
					`${model}.${field}: expected a column named "${key}" (${String(attributes.type)}, ${attributes.required ? 'required' : 'optional'})`
				);
			}
		}
		expect(
			missing,
			`better-auth ${BETTER_AUTH_VERSION} declares fields that ${SCHEMA_PATH} has no column for. ` +
				'The drizzle adapter resolves a field to a column at call time, so each one of these is a ' +
				'BetterAuthError on every read and write that touches its table, not a type error. Add the ' +
				`column to ${SCHEMA_PATH}, generate a migration, and read that file's doc comment first`
		).toEqual([]);
	});

	it('has an id column on every table', () => {
		const missing = Object.entries(TABLES)
			.filter(([, table]) => !('id' in getTableColumns(table)))
			.map(([model]) => model);
		expect(
			missing,
			`better-auth ${BETTER_AUTH_VERSION} never declares \`id\` as a field (it generates ids itself), ` +
				'but the drizzle adapter reads `schemaModel.id` directly, so a table without one fails at ' +
				'call time with no declared field to point at'
		).toEqual([]);
	});

	it('carries no column better-auth does not declare, beyond the ones that are ours', () => {
		const surplus: string[] = [];
		for (const [model, table] of Object.entries(TABLES)) {
			const declared = new Set(
				Object.entries(DECLARED[model].fields).map(([field, attributes]) =>
					columnKey(field, attributes)
				)
			);
			for (const key of Object.keys(getTableColumns(table))) {
				if (key === 'id' || declared.has(key) || key in OUR_OWN_COLUMNS[model]) continue;
				surplus.push(`${model}.${key}`);
			}
		}
		expect(
			surplus,
			`${SCHEMA_PATH} carries columns better-auth ${BETTER_AUTH_VERSION} does not declare. If the ` +
				"column is ours, add it to this file's OUR_OWN_COLUMNS with the reason it exists; if it is " +
				'not, a Better Auth upgrade dropped the field and the column is dead'
		).toEqual([]);
	});

	it('names only live, undeclared columns in its own-column allowlist', () => {
		const stale: string[] = [];
		for (const [model, own] of Object.entries(OUR_OWN_COLUMNS)) {
			const columns = getTableColumns(TABLES[model]);
			const declared = new Set(
				Object.entries(DECLARED[model].fields).map(([field, attributes]) =>
					columnKey(field, attributes)
				)
			);
			for (const key of Object.keys(own)) {
				if (!(key in columns))
					stale.push(`${model}.${key}: allowlisted but there is no such column`);
				else if (declared.has(key))
					stale.push(`${model}.${key}: allowlisted as ours, but better-auth declares it now`);
			}
		}
		expect(
			stale,
			`this file's OUR_OWN_COLUMNS is out of date against ${SCHEMA_PATH} or against better-auth ` +
				`${BETTER_AUTH_VERSION}. An allowlist nobody prunes stops being a list of decisions`
		).toEqual([]);
	});

	it('matches the type and nullability better-auth declares', () => {
		const mismatched: string[] = [];
		for (const [model, table] of Object.entries(TABLES)) {
			const columns = getTableColumns(table);
			for (const [field, attributes] of Object.entries(DECLARED[model].fields)) {
				const column = columns[columnKey(field, attributes)];
				// Absent columns are the previous test's failure, not this one's.
				if (!column) continue;
				const declaredType = String(attributes.type);
				const expectedDataType = DRIZZLE_DATA_TYPE[declaredType];
				if (!expectedDataType)
					mismatched.push(
						`${model}.${field}: declared as \`${declaredType}\`, which this guard has no drizzle equivalent for`
					);
				else if (column.dataType !== expectedDataType)
					mismatched.push(
						`${model}.${field}: declared \`${declaredType}\`, column ${column.name} is ${column.columnType} (${column.dataType})`
					);
				const required = attributes.required === true;
				if (column.notNull !== required)
					mismatched.push(
						`${model}.${field}: declared ${required ? 'required' : 'optional'}, column ${column.name} is ${column.notNull ? 'not null' : 'nullable'}`
					);
			}
		}
		expect(
			mismatched,
			`${SCHEMA_PATH} disagrees with better-auth ${BETTER_AUTH_VERSION} on type or nullability. The ` +
				'adapter only checks names, so neither of these throws on the call that hits it: a column ' +
				'that is not null where better-auth stopped writing a value fails every insert instead, and ' +
				'a nullable column where it requires one hands a null to code with no case for it'
		).toEqual([]);
	});

	it('has a unique constraint for everything better-auth declares unique', () => {
		const missing: string[] = [];
		for (const [model, table] of Object.entries(TABLES)) {
			const columns = getTableColumns(table);
			const ours = uniqueColumnSets(table);

			for (const [field, attributes] of Object.entries(DECLARED[model].fields)) {
				if (!attributes.unique) continue;
				const column = columns[columnKey(field, attributes)];
				if (!column) continue;
				if (!ours.has(normalizeColumnSet([column.name])))
					missing.push(`${model}.${field}: declared unique, column ${column.name} is not`);
			}

			for (const index of DECLARED[model].indexes ?? []) {
				if (!index.unique) continue;
				const names: string[] = [];
				for (const field of index.fields) {
					const attributes = DECLARED[model].fields[field];
					const column = columns[attributes ? columnKey(field, attributes) : field];
					if (column) names.push(column.name);
				}
				// A field with no column at all is the missing-column test's failure, not this one's.
				if (names.length !== index.fields.length) continue;
				if (!ours.has(normalizeColumnSet(names)))
					missing.push(
						`${model}: declared a unique index on (${index.fields.join(', ')}), and there is no unique constraint on (${names.join(', ')})`
					);
			}
		}
		expect(
			missing,
			`better-auth ${BETTER_AUTH_VERSION} declares uniqueness that ${SCHEMA_PATH} does not enforce. ` +
				'This is the half of #684 that is about data rather than about a failed call: without the ' +
				'constraint the same identity can be linked twice, and the migration that adds it later has ' +
				'to be told what to do about the rows that already collide'
		).toEqual([]);
	});
});
